"""
10_multihop_evaluate.py — Multi-Hop LBD Benchmark Evaluator

Loads the JSONL generated by 9_multihop_generate.py, runs FAISS retrieval
and model evaluation to produce Table 1 results.

Features:
  - FAISS entity linker (merged centroid index)
  - Endpoint-anchored retriever (checks KG reachability from start/end for each entity)
  - N models × {No-KG, +KG} evaluation
  - Bootstrap CI + McNemar test
  - JSONL checkpoint/resume

Usage:
    python 10_multihop_evaluate.py                              # all models × 2 modes
    python 10_multihop_evaluate.py --model qwen-plus            # single model
    python 10_multihop_evaluate.py --mode no_kg                 # no-KG mode only
    python 10_multihop_evaluate.py --mode plus_kg               # +KG mode only
    python 10_multihop_evaluate.py --benchmark path/to/file.jsonl
    python 10_multihop_evaluate.py --threshold 0.85             # custom FAISS threshold
"""

import argparse
import csv
import json
import os
import random
import re
import threading
import time
from collections import defaultdict, deque
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

import yaml
import numpy as np
import networkx as nx
from openai import OpenAI
from tqdm import tqdm

# ── Paths ──
WORKSPACE = Path(__file__).parent.parent
KG_JSON_DIR = WORKSPACE / "data" / "processed" / "kg"
BENCHMARK_DIR = WORKSPACE / "data" / "benchmark"
RESULTS_DIR = WORKSPACE / "results" / "table1"
MERGE_MAPPING_JSON = WORKSPACE / "data" / "processed" / "topology_sensitivity" / "phase1_merge_mapping.json"
ENTITY_EMBED_DIR = WORKSPACE / "data" / "processed" / "entity_merge_eval"
API_KEYS_YAML = WORKSPACE / "config" / "api_keys.yaml"

# ── Load configs from YAML ──
def _load_api_keys():
    with open(API_KEYS_YAML, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)

_API_CFG = _load_api_keys()

MODEL_CONFIGS = _API_CFG.get("eval_models", {})

# ── Embedding API (from YAML) ──
_embed_cfg = _API_CFG.get("embedding", {})
EMBED_API_KEY = _embed_cfg.get("api_key", "")
EMBED_API_URL = _embed_cfg.get("base_url", "").rstrip("/") + "/embeddings"
EMBED_MODEL = _embed_cfg.get("model", "text-embedding-v4")


# ============================================================
# Shared Utilities
# ============================================================

class RPMController:
    """Per-base_url sliding-window rate limiter."""
    def __init__(self, rpm: int = 200):
        self.rpm = rpm
        self._times: deque = deque()
        self._lock = threading.Lock()

    def acquire(self):
        with self._lock:
            now = time.time()
            while self._times and self._times[0] < now - 60:
                self._times.popleft()
            if len(self._times) >= self.rpm:
                wait = 60 - (now - self._times[0]) + 0.05
                if wait > 0:
                    time.sleep(wait)
            self._times.append(time.time())


class LLMClient:
    def __init__(self, cfg: dict, rpm_ctrl: RPMController):
        self.client = OpenAI(api_key=cfg["api_key"], base_url=cfg["base_url"])
        self.model = cfg["model"]
        self.rpm = rpm_ctrl
    def call(self, messages: list, max_tokens: int = 10,
             temperature: float = 0.0) -> str:
        for attempt in range(5):
            try:
                self.rpm.acquire()
                kwargs = dict(
                    model=self.model,
                    messages=messages,
                    max_tokens=max_tokens,
                    temperature=temperature,
                    timeout=60,
                )
                resp = self.client.chat.completions.create(**kwargs)
                content = resp.choices[0].message.content
                if content is None:
                    content = getattr(resp.choices[0].message, "reasoning_content", "")
                return (content or "").strip()
            except Exception as e:
                wait = min(2 ** attempt + random.random(), 30)
                print(f"  [retry {attempt+1}/5] {type(e).__name__}: {e} → sleep {wait:.1f}s")
                time.sleep(wait)
        return ""


def make_entity_readable(name: str) -> str:
    readable = re.sub(r'(?<=[a-z])(?=[A-Z])', ' ', name)
    readable = re.sub(r'(?<=[A-Z])(?=[A-Z][a-z])', ' ', readable)
    return readable


def parse_answer(text: str) -> str:
    text = text.strip().upper()
    for c in ["A", "B", "C", "D"]:
        if c in text:
            return c
    return "X"


# ============================================================
# Data Loading
# ============================================================

def load_merge_mapping() -> Dict[str, str]:
    if MERGE_MAPPING_JSON.exists():
        with open(MERGE_MAPPING_JSON, "r", encoding="utf-8") as f:
            return json.load(f)
    print("  WARNING: merge mapping not found")
    return {}


def load_kg_graph(merge_map: Dict[str, str]) -> Tuple[nx.DiGraph, Set[str]]:
    g = nx.DiGraph()
    for jf in KG_JSON_DIR.glob("*.json"):
        try:
            data = json.loads(jf.read_text(encoding="utf-8"))
            if not isinstance(data, list):
                continue
            for t in data:
                sn = merge_map.get(t.get("start_node", "").strip(),
                                   t.get("start_node", "").strip())
                en = merge_map.get(t.get("end_node", "").strip(),
                                   t.get("end_node", "").strip())
                rel = t.get("relationship", "")
                if not (sn and en and rel) or sn == en:
                    continue
                g.add_edge(sn, en, relationship=rel,
                           start_layer=t.get("start_layer", ""),
                           end_layer=t.get("end_layer", ""))
        except Exception:
            pass
    return g, set(g.nodes())


def load_benchmark(path: Path) -> List[dict]:
    questions = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                questions.append(json.loads(line))
    return questions


# ============================================================
# FAISS Entity Linker
# ============================================================

class FAISSLinker:
    """FAISS-based entity linker using merged centroid embeddings."""

    def __init__(self, kg_graph: nx.DiGraph, merge_map: Dict[str, str],
                 threshold: float = 0.82):
        import faiss as _faiss
        self.faiss = _faiss
        self.threshold = threshold
        self._build_merged_index(kg_graph, merge_map)

        import requests as _requests
        self._requests = _requests

    def _build_merged_index(self, kg_graph: nx.DiGraph, merge_map: Dict[str, str]):
        entities_path = ENTITY_EMBED_DIR / "entities.json"
        embeddings_path = ENTITY_EMBED_DIR / "embeddings.npy"

        with open(entities_path, "r", encoding="utf-8") as f:
            orig_data = json.load(f)
        orig_entities = orig_data["entities"]
        orig_embeddings = np.load(str(embeddings_path)).astype("float32")

        entity_to_idx = {e: i for i, e in enumerate(orig_entities)}

        # Group by canonical name
        canonical_groups: Dict[str, List[int]] = {}
        for e in orig_entities:
            canon = merge_map.get(e, e)
            if canon not in canonical_groups:
                canonical_groups[canon] = []
            canonical_groups[canon].append(entity_to_idx[e])

        # Only keep KG nodes
        kg_node_set = set(kg_graph.nodes())
        self.nodes: List[str] = []
        centroids_list = []

        for canon, indices in sorted(canonical_groups.items()):
            if canon not in kg_node_set:
                continue
            group_vecs = orig_embeddings[indices]
            centroid = group_vecs.mean(axis=0)
            self.nodes.append(canon)
            centroids_list.append(centroid)

        centroids = np.array(centroids_list, dtype="float32")
        self.faiss.normalize_L2(centroids)
        self.index = self.faiss.IndexFlatIP(centroids.shape[1])
        self.index.add(centroids)
        self._node_set = set(self.nodes)

        print(f"  FAISS index: {self.index.ntotal} merged entities (threshold={self.threshold})")

    def _get_embedding(self, text: str) -> np.ndarray:
        headers = {"Authorization": f"Bearer {EMBED_API_KEY}",
                   "Content-Type": "application/json"}
        payload = {"model": EMBED_MODEL, "input": [text], "encoding_format": "float"}
        try:
            resp = self._requests.post(EMBED_API_URL, headers=headers,
                                       json=payload, timeout=15)
            if resp.status_code == 200:
                return np.array(resp.json()["data"][0]["embedding"], dtype=np.float32)
        except Exception:
            pass
        return np.zeros(1024, dtype=np.float32)

    def _get_embeddings_batch(self, texts: List[str]) -> List[np.ndarray]:
        """Batch embed multiple texts. DashScope allows max 10 per call."""
        if not texts:
            return []
        BATCH_MAX = 10
        all_embeddings = []
        for i in range(0, len(texts), BATCH_MAX):
            chunk = texts[i:i + BATCH_MAX]
            headers = {"Authorization": f"Bearer {EMBED_API_KEY}",
                       "Content-Type": "application/json"}
            payload = {"model": EMBED_MODEL, "input": chunk, "encoding_format": "float"}
            try:
                resp = self._requests.post(EMBED_API_URL, headers=headers,
                                           json=payload, timeout=30)
                if resp.status_code == 200:
                    data = resp.json()["data"]
                    sorted_data = sorted(data, key=lambda x: x["index"])
                    all_embeddings.extend([np.array(d["embedding"], dtype=np.float32) for d in sorted_data])
                else:
                    all_embeddings.extend([np.zeros(1024, dtype=np.float32) for _ in chunk])
            except Exception:
                all_embeddings.extend([np.zeros(1024, dtype=np.float32) for _ in chunk])
        return all_embeddings

    def link(self, text: str) -> Tuple[Optional[str], float]:
        """Link natural language text to KG node.
        Returns (node_name, score) or (None, score) if below threshold.
        """
        vec = self._get_embedding(text).reshape(1, -1)
        self.faiss.normalize_L2(vec)
        scores, idxs = self.index.search(vec, 1)
        idx = idxs[0][0]
        score = float(scores[0][0])
        if idx >= 0 and idx < len(self.nodes) and score >= self.threshold:
            return self.nodes[idx], score
        return None, score

    def link_batch(self, texts: List[str]) -> List[Tuple[Optional[str], float]]:
        """Batch link: 1 API call for all texts, then per-text FAISS search.
        Reduces API calls from N to 1 per question.
        """
        embeddings = self._get_embeddings_batch(texts)
        results = []
        for vec in embeddings:
            vec = vec.reshape(1, -1)
            self.faiss.normalize_L2(vec)
            scores, idxs = self.index.search(vec, 1)
            idx = idxs[0][0]
            score = float(scores[0][0])
            if idx >= 0 and idx < len(self.nodes) and score >= self.threshold:
                results.append((self.nodes[idx], score))
            else:
                results.append((None, score))
        return results


# ============================================================
# Path-Aware Retriever
# ============================================================

class PathAwareRetriever:
    """Endpoint-Anchored Retrieval: checks EVERY option entity's connectivity
    to both start and end via KG.

    Unified strategy for 1/2/3/4-hop:
    - For each option entity e_i, check reachability to Start and End
    - Use single_source_shortest_path (2 BFS per question, not per entity)
    - Report direct edges with relationship labels (strong signal)
    - Report indirect paths ≤4 steps (weak signal)
    - Do NOT check internal edges between option entities
      (distractors from KG random walk have 100% internal connectivity,
       so internal edges provide zero discriminative signal)
    """

    def __init__(self, kg_G: nx.DiGraph, faiss_linker: FAISSLinker):
        self.kg = kg_G
        self.linker = faiss_linker
        self._undirected = kg_G.to_undirected()
        self._embed_rpm = RPMController(500)

    def _format_path_with_rels(self, path_nodes: list) -> str:
        """Format a path with relationship labels from the directed graph."""
        parts = []
        for i, node in enumerate(path_nodes):
            node_text = make_entity_readable(node)
            if i < len(path_nodes) - 1:
                u, v = node, path_nodes[i + 1]
                if self.kg.has_edge(u, v):
                    rel = self.kg[u][v].get("relationship", "related_to")
                    parts.append(f"{node_text} -[{rel}]->")
                elif self.kg.has_edge(v, u):
                    rel = self.kg[v][u].get("relationship", "related_to")
                    parts.append(f"{node_text} <-[{rel}]-")
                else:
                    parts.append(f"{node_text} -->")
            else:
                parts.append(node_text)
        return " ".join(parts)

    def _get_entity_evidence(self, entity_node: Optional[str], entity_text: str,
                             paths_from_start: dict, paths_from_end: dict,
                             start_text: str, end_text: str) -> Tuple[List[str], bool]:
        """Get KG evidence for one entity's connectivity to start and end."""
        lines = []
        has_evidence = False

        if entity_node is None:
            lines.append(f"    (not found in KG)")
            return lines, False

        # ── Connectivity to Start ──
        if entity_node in paths_from_start:
            path = paths_from_start[entity_node]
            path_len = len(path) - 1  # number of edges
            if path_len == 1:
                # Direct edge (strong signal)
                path_str = self._format_path_with_rels(path)
                lines.append(f"    ↔ Start: DIRECT ({path_str})")
            elif path_len <= 3:
                # Indirect path (weak signal)
                path_str = self._format_path_with_rels(path)
                lines.append(f"    ↔ Start: {path_len} steps ({path_str})")
            has_evidence = True
        else:
            lines.append(f"    ↔ Start: no path found in KG (>4 steps)")

        # ── Connectivity to End ──
        if paths_from_end is not None:
            if entity_node in paths_from_end:
                path = paths_from_end[entity_node]
                path_len = len(path) - 1
                # Reverse path direction for display (end→...→entity becomes entity→...→end)
                display_path = list(reversed(path))
                if path_len == 1:
                    path_str = self._format_path_with_rels(display_path)
                    lines.append(f"    ↔ End: DIRECT ({path_str})")
                elif path_len <= 3:
                    path_str = self._format_path_with_rels(display_path)
                    lines.append(f"    ↔ End: {path_len} steps ({path_str})")
                has_evidence = True
            else:
                lines.append(f"    ↔ End: no path found in KG (>4 steps)")

        return lines, has_evidence

    def get_context(self, question: dict) -> str:
        """Build endpoint-anchored evidence for all 4 options.

        Per question: 1-2 API calls (batch embed) + 2 BFS (single_source_shortest_path).
        """
        start = question["start_entity"]
        end = question.get("end_entity")
        hop = question["hop_count"]

        if hop == 1:
            end = None

        start_text = make_entity_readable(start)
        end_text = make_entity_readable(end) if end else ""

        # ── Batch embed all unique entities ──
        all_texts = [start_text]
        if end:
            all_texts.append(end_text)

        option_entity_map = []
        for opt in question["options"]:
            readable_entities = [make_entity_readable(e) for e in opt["entities"]]
            start_idx = len(all_texts)
            all_texts.extend(readable_entities)
            option_entity_map.append((start_idx, len(readable_entities), readable_entities))

        self._embed_rpm.acquire()
        all_linked = self.linker.link_batch(all_texts)

        s_node, _ = all_linked[0]
        if end:
            e_node, _ = all_linked[1]
        else:
            e_node = None

        # ── 2 BFS calls: paths from start and from end (cutoff=4) ──
        paths_from_start = {}
        if s_node and s_node in self._undirected:
            paths_from_start = nx.single_source_shortest_path(
                self._undirected, s_node, cutoff=4)

        paths_from_end = None
        if e_node and e_node in self._undirected:
            paths_from_end = nx.single_source_shortest_path(
                self._undirected, e_node, cutoff=4)

        # ── Build evidence for each option ──
        lines = []
        if end:
            lines.append(f"=== KG Evidence: {start_text} → ... → {end_text} ===")
        else:
            lines.append(f"=== KG Evidence: {start_text} → ? ===")
        lines.append("")

        for i, opt in enumerate(question["options"]):
            letter = opt["label"]
            opt_text = opt["text"]
            idx_start, count, readable_ents = option_entity_map[i]
            o_nodes = all_linked[idx_start: idx_start + count]

            lines.append(f"--- Option {letter}: {opt_text} ---")
            option_has_evidence = False

            for j, (entity_node_score, ent_text) in enumerate(zip(o_nodes, readable_ents)):
                entity_node, score = entity_node_score
                lines.append(f"  {ent_text}:")
                ent_lines, has_ev = self._get_entity_evidence(
                    entity_node, ent_text,
                    paths_from_start, paths_from_end,
                    start_text, end_text,
                )
                lines.extend(ent_lines)
                if has_ev:
                    option_has_evidence = True

            if not option_has_evidence:
                lines.append("  (no KG evidence found)")
            lines.append("")

        # ── Additional Context: start/end neighborhoods ──
        lines.append("--- Additional Context ---")
        if s_node and s_node in self.kg:
            for succ in list(self.kg.successors(s_node))[:5]:
                rel = self.kg[s_node][succ].get("relationship", "")
                lines.append(f"  {start_text} -[{rel}]-> {make_entity_readable(succ)}")
            for pred in list(self.kg.predecessors(s_node))[:3]:
                rel = self.kg[pred][s_node].get("relationship", "")
                lines.append(f"  {make_entity_readable(pred)} -[{rel}]-> {start_text}")

        if e_node and e_node in self.kg:
            for pred in list(self.kg.predecessors(e_node))[:5]:
                rel = self.kg[pred][e_node].get("relationship", "")
                lines.append(f"  {make_entity_readable(pred)} -[{rel}]-> {end_text}")
            for succ in list(self.kg.successors(e_node))[:3]:
                rel = self.kg[e_node][succ].get("relationship", "")
                lines.append(f"  {end_text} -[{rel}]-> {make_entity_readable(succ)}")

        return "\n".join(lines)


# ============================================================
# Prompt Templates
# ============================================================

PROMPT_NO_KG = """Answer the following multiple-choice question about heatwave cascading risks.

{question_with_options}

Instructions:
1. Analyze based on your knowledge of climate science and disaster risk.
2. Select the most plausible answer.

IMPORTANT: Respond with ONLY a single letter: A, B, C, or D. Do not write any explanation."""

PROMPT_PLUS_KG = """Answer the following multiple-choice question about heatwave cascading risks.

Historical knowledge graph (KG) evidence is provided below.
{evidence_block}

INSTRUCTIONS FOR SYNTHESIS:
1. The KG is highly accurate but structurally incomplete (sparse).
2. Strong KG Connections: If an option has "DIRECT" or short paths (2-3 steps) to the Start and End entities, this is STRONG structural evidence of a valid causal chain. Prioritize these options.
3. Missing KG Connections: "No path found" DOES NOT mean the relationship is impossible—it simply means it is missing from this specific KG.
4. If no option shows strong KG connections to the endpoints, or if you are evaluating options with weak paths, FALL BACK to your own expert knowledge of climate science and disaster risk to determine the most logically coherent pathway.

{question_with_options}

IMPORTANT: Respond with ONLY a single letter: A, B, C, or D. Do not write any explanation."""


# ============================================================
# Evaluation Loop (with checkpoint/resume)
# ============================================================

def evaluate(
    model_name: str,
    questions: List[dict],
    llm: LLMClient,
    retriever: Optional[PathAwareRetriever],
    mode: str,  # "no_kg" or "plus_kg"
    output_jsonl: Path,
) -> List[dict]:
    """Run evaluation with JSONL checkpoint/resume."""
    # Load existing results for resume
    done_ids = set()
    if output_jsonl.exists():
        with open(output_jsonl, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line:
                    rec = json.loads(line)
                    done_ids.add(rec["id"])
        print(f"  Resuming: {len(done_ids)} already done, {len(questions) - len(done_ids)} remaining")

    todo = [q for q in questions if q["id"] not in done_ids]
    if not todo:
        print(f"  All {len(questions)} questions already completed!")
        # Load all results
        results = []
        with open(output_jsonl, "r", encoding="utf-8") as f:
            for line in f:
                if line.strip():
                    results.append(json.loads(line))
        return results

    use_kg = (mode == "plus_kg")
    correct_count = sum(1 for _ in [])  # will count below
    file_lock = threading.Lock()

    # Load existing results into memory
    results = []
    if done_ids:
        with open(output_jsonl, "r", encoding="utf-8") as f:
            for line in f:
                if line.strip():
                    results.append(json.loads(line))
        correct_count = sum(1 for r in results if r.get("correct"))

    def process_one(q: dict) -> dict:
        # Build question text with options
        opts_lines = []
        for opt in q["options"]:
            opts_lines.append(f"{opt['label']}. {opt['text']}")
        q_with_opts = q["question"] + "\n" + "\n".join(opts_lines)

        if use_kg and retriever:
            ctx = retriever.get_context(q)
            prompt = PROMPT_PLUS_KG.format(
                evidence_block=ctx,
                question_with_options=q_with_opts,
            )
        else:
            prompt = PROMPT_NO_KG.format(question_with_options=q_with_opts)

        raw = llm.call([{"role": "user", "content": prompt}])
        predicted = parse_answer(raw)

        rec = {
            "id": q["id"],
            "hop_count": q["hop_count"],
            "predicted": predicted,
            "expected": q["answer"],
            "correct": predicted == q["answer"],
            "raw_response": raw[:50],
        }

        # Append to JSONL (thread-safe)
        with file_lock:
            with open(output_jsonl, "a", encoding="utf-8") as f:
                f.write(json.dumps(rec, ensure_ascii=False) + "\n")

        return rec

    desc = f"{model_name} ({mode})"
    with ThreadPoolExecutor(max_workers=6) as pool:
        futures = {pool.submit(process_one, q): q["id"] for q in todo}
        pbar = tqdm(total=len(todo), desc=desc, ncols=90)
        for fut in as_completed(futures):
            rec = fut.result()
            results.append(rec)
            if rec["correct"]:
                correct_count += 1
            total_done = len(results)
            pbar.set_postfix(acc=f"{correct_count}/{total_done}")
            pbar.update(1)
        pbar.close()

    return results


# ============================================================
# Metrics
# ============================================================

def compute_metrics(records: List[dict]) -> dict:
    total = len(records)
    correct = sum(1 for r in records if r["correct"])
    failed = sum(1 for r in records if r["predicted"] == "X")
    valid = total - failed
    accuracy = correct / valid * 100 if valid > 0 else 0

    # Macro F1
    labels = ["A", "B", "C", "D"]
    f1_scores = []
    for label in labels:
        tp = sum(1 for r in records if r["predicted"] == label and r["expected"] == label)
        fp = sum(1 for r in records if r["predicted"] == label and r["expected"] != label)
        fn = sum(1 for r in records if r["expected"] == label and r["predicted"] != label)
        prec = tp / (tp + fp) if (tp + fp) > 0 else 0
        rec = tp / (tp + fn) if (tp + fn) > 0 else 0
        f1 = 2 * prec * rec / (prec + rec) if (prec + rec) > 0 else 0
        f1_scores.append(f1)
    macro_f1 = sum(f1_scores) / len(f1_scores)

    # Per-hop
    by_hop = defaultdict(list)
    for r in records:
        by_hop[r["hop_count"]].append(r)
    per_hop = {}
    for h in sorted(by_hop.keys()):
        hc = sum(1 for r in by_hop[h] if r["correct"])
        ht = len(by_hop[h])
        hf = sum(1 for r in by_hop[h] if r["predicted"] == "X")
        hv = ht - hf
        per_hop[str(h)] = {
            "total": ht, "correct": hc, "failed": hf,
            "accuracy": round(hc / hv * 100, 2) if hv > 0 else 0,
        }

    return {
        "total": total, "correct": correct, "failed": failed,
        "accuracy": round(accuracy, 2),
        "f1_macro": round(macro_f1, 4),
        "per_hop": per_hop,
    }


def bootstrap_ci(records: List[dict], n_bootstrap: int = 2000,
                 seed: int = 42) -> Tuple[float, float]:
    """95% Bootstrap CI for accuracy."""
    rng = np.random.RandomState(seed)
    n = len(records)
    accs = []
    for _ in range(n_bootstrap):
        sample = rng.choice(records, size=n, replace=True)
        valid = [r for r in sample if r["predicted"] != "X"]
        if valid:
            accs.append(sum(1 for r in valid if r["correct"]) / len(valid) * 100)
    return round(np.percentile(accs, 2.5), 2), round(np.percentile(accs, 97.5), 2)


def paired_delta_bootstrap(records_no_kg: List[dict], records_kg: List[dict],
                           n_bootstrap: int = 2000, seed: int = 42) -> Tuple[float, float, float]:
    """Paired bootstrap delta (KG - No-KG) with 95% CI."""
    # Align by id
    nokg_map = {r["id"]: r for r in records_no_kg}
    kg_map = {r["id"]: r for r in records_kg}
    common_ids = sorted(set(nokg_map.keys()) & set(kg_map.keys()))

    rng = np.random.RandomState(seed)
    deltas = []
    for _ in range(n_bootstrap):
        ids = rng.choice(common_ids, size=len(common_ids), replace=True)
        c_nokg = sum(1 for i in ids if nokg_map[i]["correct"])
        c_kg = sum(1 for i in ids if kg_map[i]["correct"])
        n = len(ids)
        deltas.append((c_kg - c_nokg) / n * 100)

    mean_delta = round(np.mean(deltas), 2)
    ci_lo = round(np.percentile(deltas, 2.5), 2)
    ci_hi = round(np.percentile(deltas, 97.5), 2)
    return mean_delta, ci_lo, ci_hi


def mcnemar_test(records_no_kg: List[dict], records_kg: List[dict]) -> float:
    """McNemar's test p-value."""
    from scipy import stats as scipy_stats

    nokg_map = {r["id"]: r["correct"] for r in records_no_kg}
    kg_map = {r["id"]: r["correct"] for r in records_kg}
    common_ids = sorted(set(nokg_map.keys()) & set(kg_map.keys()))

    # b = no_kg correct, kg wrong; c = no_kg wrong, kg correct
    b = sum(1 for i in common_ids if nokg_map[i] and not kg_map[i])
    c = sum(1 for i in common_ids if not nokg_map[i] and kg_map[i])

    if b + c == 0:
        return 1.0

    # McNemar with continuity correction
    chi2 = (abs(b - c) - 1) ** 2 / (b + c)
    p_value = 1 - scipy_stats.chi2.cdf(chi2, df=1)
    return p_value


# ============================================================
# Main
# ============================================================

def main():
    parser = argparse.ArgumentParser(description="Multi-Hop LBD Benchmark Evaluator → Table 1")
    parser.add_argument("--benchmark", type=str, default=None,
                        help="Benchmark JSONL path")
    parser.add_argument("--model", type=str, nargs="+", default=None,
                        help="Model(s) to evaluate (default: all)")
    parser.add_argument("--mode", type=str, nargs="+", default=["no_kg", "plus_kg"],
                        choices=["no_kg", "plus_kg"],
                        help="Evaluation mode(s)")
    parser.add_argument("--threshold", type=float, default=0.82,
                        help="FAISS linking threshold")
    parser.add_argument("--rpm", type=int, default=200, help="RPM per provider")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    random.seed(args.seed)

    # Determine benchmark path
    bench_path = Path(args.benchmark) if args.benchmark else BENCHMARK_DIR / "multihop_lbd.jsonl"
    if not bench_path.exists():
        print(f"ERROR: Benchmark not found: {bench_path}")
        print(f"  Run 9_multihop_generate.py first.")
        return

    # Load benchmark
    print(f"Loading benchmark: {bench_path}")
    questions = load_benchmark(bench_path)
    print(f"  {len(questions)} questions loaded")

    hop_counts = defaultdict(int)
    for q in questions:
        hop_counts[q["hop_count"]] += 1
    for h in sorted(hop_counts):
        print(f"  {h}-hop: {hop_counts[h]}")

    # Determine models
    models = args.model if args.model else list(MODEL_CONFIGS.keys())
    modes = args.mode

    print(f"\nExperiment matrix: {len(models)} models × {len(modes)} modes = {len(models) * len(modes)} experiments")

    # ── Load KG + FAISS (if needed) ──
    retriever = None
    if "plus_kg" in modes:
        print("\n[Setup] Loading KG + FAISS Entity Linker ...")
        merge_map = load_merge_mapping()
        print(f"  Merge mapping: {len(merge_map)} entries")
        kg_G, kg_nodes = load_kg_graph(merge_map)
        print(f"  KG: {kg_G.number_of_nodes()} nodes, {kg_G.number_of_edges()} edges")

        linker = FAISSLinker(kg_G, merge_map, threshold=args.threshold)
        retriever = PathAwareRetriever(kg_G, linker)
        print(f"  Path-Aware Retriever initialized")
    else:
        merge_map = {}

    # ── RPM controllers per base_url ──
    rpm_ctrls: Dict[str, RPMController] = {}
    for m in models:
        base_url = MODEL_CONFIGS[m]["base_url"]
        if base_url not in rpm_ctrls:
            rpm_ctrls[base_url] = RPMController(args.rpm)

    # ── Run experiments ──
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    all_results: Dict[str, Dict[str, List[dict]]] = {}  # model -> mode -> records

    for model_name in models:
        all_results[model_name] = {}
        cfg = MODEL_CONFIGS[model_name]
        rpm_ctrl = rpm_ctrls[cfg["base_url"]]
        llm = LLMClient(cfg, rpm_ctrl)

        for mode in modes:
            safe_name = model_name.replace("/", "-")
            output_jsonl = RESULTS_DIR / f"eval_{safe_name}_{mode}.jsonl"

            print(f"\n{'='*60}")
            print(f"  {model_name} | {mode} | {len(questions)} questions")
            print(f"  Output: {output_jsonl}")
            print(f"{'='*60}")

            records = evaluate(
                model_name, questions, llm,
                retriever if mode == "plus_kg" else None,
                mode, output_jsonl,
            )
            all_results[model_name][mode] = records

            metrics = compute_metrics(records)
            print(f"\n  Accuracy: {metrics['accuracy']}%  F1: {metrics['f1_macro']}  Failed: {metrics['failed']}")
            for h in sorted(metrics["per_hop"]):
                ph = metrics["per_hop"][h]
                print(f"  {h}-hop: {ph['accuracy']}% ({ph['correct']}/{ph['total']})")

    # ── Summary Table ──
    print(f"\n\n{'='*80}")
    print(f"  TABLE 1 SUMMARY")
    print(f"{'='*80}")

    summary_rows = []
    header = f"{'Model':<22} {'Mode':<8} "
    for h in sorted(hop_counts):
        header += f"{'%d-hop' % h:>8} "
    header += f"{'Overall':>9} {'Delta':>8} {'p-value':>8}"
    print(header)
    print("-" * len(header))

    for model_name in models:
        for mode in modes:
            records = all_results.get(model_name, {}).get(mode, [])
            if not records:
                continue
            metrics = compute_metrics(records)

            row = f"{model_name:<22} {mode:<8} "
            for h in sorted(hop_counts):
                acc = metrics["per_hop"].get(str(h), {}).get("accuracy", 0)
                row += f"{acc:>7.1f}% "

            row += f"{metrics['accuracy']:>8.1f}%"

            # Delta and p-value (only for +KG)
            delta_str = ""
            p_str = ""
            if mode == "plus_kg" and "no_kg" in all_results.get(model_name, {}):
                nokg_records = all_results[model_name]["no_kg"]
                nokg_metrics = compute_metrics(nokg_records)
                delta = metrics["accuracy"] - nokg_metrics["accuracy"]
                delta_str = f"{'+' if delta >= 0 else ''}{delta:.1f}%"
                try:
                    p_val = mcnemar_test(nokg_records, records)
                    p_str = f"<.001" if p_val < 0.001 else f"{p_val:.3f}"
                except Exception:
                    p_str = "N/A"

            row += f" {delta_str:>8} {p_str:>8}"
            print(row)

            # Bootstrap CI
            ci_lo, ci_hi = bootstrap_ci(records)

            summary_rows.append({
                "model": model_name,
                "mode": mode,
                "accuracy": metrics["accuracy"],
                "f1_macro": metrics["f1_macro"],
                "failed": metrics["failed"],
                "ci_95": f"[{ci_lo}, {ci_hi}]",
                "delta": delta_str,
                "p_value": p_str,
                "per_hop": metrics["per_hop"],
            })

    # ── Save summary ──
    summary_json = RESULTS_DIR / "table1_summary.json"
    with open(summary_json, "w", encoding="utf-8") as f:
        json.dump(summary_rows, f, indent=2, ensure_ascii=False)
    print(f"\n  Summary JSON: {summary_json}")

    # CSV
    summary_csv = RESULTS_DIR / "table1_summary.csv"
    with open(summary_csv, "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        hop_headers = [f"{h}-hop" for h in sorted(hop_counts)]
        writer.writerow(["Model", "Mode"] + hop_headers + ["Overall", "F1", "CI_95", "Delta", "p-value"])
        for row in summary_rows:
            hop_accs = [str(row["per_hop"].get(str(h), {}).get("accuracy", "")) for h in sorted(hop_counts)]
            writer.writerow([
                row["model"], row["mode"],
            ] + hop_accs + [
                row["accuracy"], row["f1_macro"], row["ci_95"],
                row["delta"], row["p_value"],
            ])
    print(f"  Summary CSV:  {summary_csv}")

    # Markdown
    summary_md = RESULTS_DIR / "table1_summary.md"
    with open(summary_md, "w", encoding="utf-8") as f:
        hop_headers = [f"{h}-hop" for h in sorted(hop_counts)]
        f.write("| Model | Mode | " + " | ".join(hop_headers) + " | Overall | Delta | p |\n")
        f.write("|-------|------|" + "|".join(["--------"] * len(hop_headers)) + "|---------|-------|---|\n")
        for row in summary_rows:
            hop_accs = [f"{row['per_hop'].get(str(h), {}).get('accuracy', 0):.1f}%" for h in sorted(hop_counts)]
            f.write(f"| {row['model']} | {row['mode']} | " +
                    " | ".join(hop_accs) +
                    f" | {row['accuracy']:.1f}% | {row['delta']} | {row['p_value']} |\n")
    print(f"  Summary MD:   {summary_md}")

    print(f"\n{'='*80}")
    print(f"  Done! All results in: {RESULTS_DIR}/")
    print(f"{'='*80}")


if __name__ == "__main__":
    main()
